export const AppStoreKey = {
    SET_CALENDAR_ENTRIES: 'SET_CALENDAR_ENTRIES',
    ADD_CALENDAR_ENTRY: 'ADD_CALENDAR_ENTRY',
    REMOVE_CALENDAR_ENTRY: 'REMOVE_CALENDAR_ENTRY',

    SET_COOKBOOK_RECIPES: 'SET_COOKBOOK_RECIPES',
    ADD_COOKBOOK_RECIPE: 'ADD_COOKBOOK_RECIPE',
    REMOVE_COOKBOOK_RECIPE: 'REMOVE_COOKBOOK_RECIPE',
}
